# Generated by Django 3.2.8 on 2021-10-31 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsDetails',
            new_name='NewsDetail',
        ),
    ]
