# Generated by Django 3.2.8 on 2021-10-31 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_newsdetails_newsdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsdetail',
            old_name='Category',
            new_name='category',
        ),
    ]
